modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Bread-Nicecat/CandyCraftCE/issues"
license = "GNU LGPL v3"

[[mods]]
modId = "candycraftce"
version = "${version}"
displayName = "CandyCraft CE"
authors = "Bread_NiceCat, Star_Ocean_Sama(Texture)"
credits = "Architectury-Loom"
description = '''
'''
logoFile = "icon.png"

[[dependencies.candycraftce]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candycraftce]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"