name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          
      - name: draw jars
        run: ./gradlew drawJars
      - name: upload full
        uses: actions/upload-artifact@v3
        with:
          name: all
          path: build/buildJars
          if-no-files-found: error

      - name: upload forge
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: build/buildJars/modJars/forge/*.jar
          if-no-files-found: error

      - name: upload fabric
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: build/buildJars/modJars/fabric/*.jar
          if-no-files-found: error

